doctrine:
    dbal:
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        host: '%env(resolve:PARAMETERS_DATABASE_HOST)%'
        port: '%env(resolve:PARAMETERS_DATABASE_PORT)%'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
        driver: pdo_mysql
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        options:
            collate: utf8mb4_unicode_ci
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Common:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Common/Domain'
                prefix: 'Jefero\Bot@\Common\Domain'
                alias: Common
            Main:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Main/Domain'
                prefix: 'Jefero\Bot\Main\Domain'
                alias: Main
